# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: bindings/pydeck/docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: bindings/pydeck/requirements-dev.txt
