matrix:
  include:
    - language: node_js
      dist: precise
      os: linux
      group: stable
      sudo: required
      dist: trusty
      env:
        - CXX=g++-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - mesa-utils
          - xvfb
          - libgl1-mesa-dri
          - libglapi-mesa
          - libosmesa6
          - libxi-dev
      install:
        - yarn bootstrap
      node_js:
        - 12.12.0
      before_script:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
        - ulimit -c unlimited -S       # enable core dumps
      script:
        - npm run test ci
      after_success:
        - cat coverage/lcov.info | coveralls

    - language: python
      dist: xenial
      os: linux
      group: stable
      sudo: required
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
      before_install:
        - cd bindings/pydeck
      python:
        - "3.7"
      cache:
        pip: true
        directories:
          - ~/.npm  # NPM cache
      install:
        - nvm install 12.12.0
        - nvm use 12.12.0
        - make init
      script: make test
